### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by Demuos** [Spritetm/printercart_simple#2]
I´m having a hard time trying to compile your unmodified code in Ubuntu ESP-IDF. Do I have to set something specific to compile the code?

I´m getting the following errors:

`/home/demos/esp/printercart_simple/main/main.c: In function 'button_pressed':

/home/demos/esp/printercart_simple/main/main.c:138:11: error: implicit declaration of function 'gpio_get_level'; did you mean '_xtos_set_intlevel'? [-Werror=implicit-function-declaration]
  return (!gpio_get_level(PIN_NUM_BTN));
           ^~~~~~~~~~~~~~
           _xtos_set_intlevel
/home/demos/esp/printercart_simple/main/main.c: In function 'button_init':
/home/demos/esp/printercart_simple/main/main.c:143:2: error: unknown type name 'gpio_config_t'
  gpio_config_t io_conf={
  ^~~~~~~~~~~~~
/home/demos/esp/printercart_simple/main/main.c:144:3: error: field name not in record or union initializer
   .mode=GPIO_MODE_INPUT,
   ^
/home/demos/esp/printercart_simple/main/main.c:144:3: note: (near initialization for 'io_conf')
/home/demos/esp/printercart_simple/main/main.c:144:9: error: 'GPIO_MODE_INPUT' undeclared (first use in this function)
   .mode=GPIO_MODE_INPUT,
         ^~~~~~~~~~~~~~~
/home/demos/esp/printercart_simple/main/main.c:144:9: note: each undeclared identifier is reported only once for each function it appears in
/home/demos/esp/printercart_simple/main/main.c:145:3: error: field name not in record or union initializer
   .pin_bit_mask=(1ULL<<PIN_NUM_BTN),
   ^
/home/demos/esp/printercart_simple/main/main.c:145:3: note: (near initialization for 'io_conf')
/home/demos/esp/printercart_simple/main/main.c:145:17: warning: excess elements in scalar initializer
   .pin_bit_mask=(1ULL<<PIN_NUM_BTN),
                 ^
/home/demos/esp/printercart_simple/main/main.c:145:17: note: (near initialization for 'io_conf')
/home/demos/esp/printercart_simple/main/main.c:146:3: error: field name not in record or union initializer
   .pull_up_en=1,
   ^
/home/demos/esp/printercart_simple/main/main.c:146:3: note: (near initialization for 'io_conf')
/home/demos/esp/printercart_simple/main/main.c:146:15: warning: excess elements in scalar initializer
   .pull_up_en=1,
               ^
/home/demos/esp/printercart_simple/main/main.c:146:15: note: (near initialization for 'io_conf')
/home/demos/esp/printercart_simple/main/main.c:148:2: error: implicit declaration of function 'gpio_config' [-Werror=implicit-function-declaration]
  gpio_config(&io_conf);
  ^~~~~~~~~~~
cc1: some warnings being treated as errors
make[1]: *** [/home/demos/esp/esp-idf/make/component_wrapper.mk:292: main.o] Error 1
make: *** [/home/demos/esp/esp-idf/make/project.mk:635: component-main-build] Error 2`

**Comment by Spritetm** [comment]
Given the fact that this project is 3 years old, it probably developed some incompatibilities with recent ESP-IDF versions. Can you try pulling and compiling again? No guarantees to if it still works, but it should at least compile cleanly.

**Comment by Demuos** [comment]
Thank you for your help, compiling now worked. Hopefully it still works with the board.
